version: '3.7'

services:
  server:
    image: luissaybe/tf-connect4
    ports:
      - "8000:8000"
    volumes:
       - ./model:/tmp/model
  trainer:
    image: luissaybe/tf-connect4
    command: python3 src/train.py 5000000000 30
    volumes:
       - ./model:/tmp/model

volumes:
  model:
