version: '3.7'

services:
  trainer:
    build:
      context: .
    command: python3 src/train.py 1000000
    container_name: connnect-4-trainer
    working_dir: /tmp/project
    volumes:
       - .:/tmp/project
  tensorboard:
    build:
      context: .
    command: tensorboard --bind_all --logdir /tmp/project/logs
    container_name: connnect-4-tensorboard
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
       - .:/tmp/project
