version: '3.7'

services:
  trainer:
    image: luissaybe/connect-4-reinforcement-learning
    command: python3 /tmp/project/src/train.py 1000 1000
    volumes:
       - .:/tmp/project
  tensorboard:
    image: luissaybe/connect-4-reinforcement-learning
    command: tensorboard --bind_all --logdir /tmp/project/logs
    ports:
      - "6006:6006"
    volumes:
       - ./logs:/tmp/project/logs
