version: '3.7'

services:
  trainer:
    image: luissaybe/connect-4-reinforcement-learning
    command: python3 src/train.py 1000000 10
    working_dir: /tmp/project
    volumes:
       - ./logs:/tmp/project/logs
  tensorboard:
    image: luissaybe/connect-4-reinforcement-learning
    command: tensorboard --bind_all --logdir /tmp/project/logs
    ports:
      - "6006:6006"
    volumes:
       - ./logs:/tmp/project/logs
